### ISSUE TITLE
[perf] Why noDiff?

### ISSUE THREAD

**Issue by jablko** [microsoft/DefinitelyTyped-tools#166]
@andrewbranch Just curious why [`noDiff` was added](https://github.com/andrewbranch/definitely-not-slow/commit/2856105025ba3b27728159a072478c2cb2696176#diff-d04828f8e0791f56be0fa9eccab7ddcf2548a31a7a9510aa56583d33834488b1R201) to the `completionsAvgCV` metric? It's not obvious to me from the history ...

**Comment by andrewbranch** [comment]
Good question! Mainly because the values are already expressed in percentages, and expressing the percent difference between two percentages can be confusing/misleading—from dimensional analysis you can’t tell whether it’s a ratio or a simple arithmetic difference, and it’s somewhat unclear which would be the better measure of change. Secondly, since the CV only measures noise in the system, it’s not something the definition authors are responsible for, and a change in its value indicates nothing about the code change of the PR. A high value in either column should lead someone to view the other measurements in that column with a higher degree of skepticism. A significant _difference_ between the CV before and after might lead you to believe that comparing other before and after values might be unreliable, but in fact, that comparison would be more reliable than if the CV before and after are _both_ high. So paying attention to the difference at all is misleading, unless you are trying to debug the measurement infrastructure itself.

**Comment by jablko** [comment]
Thanks for the answer! Makes sense. Should it be added to `quickInfoAvgCV` as well then? https://github.com/microsoft/DefinitelyTyped-tools/blob/a02b2e92ab4498daba3baf643f1e9bd6202a6b3f/packages/perf/src/analysis/metrics.ts#L254

**Comment by andrewbranch** [comment]
Oh, yes, good catch. Neither of those measurements should report a diff.
