### ISSUE TITLE
https://typespublisher.blob.core.windows.net/ is unavailable

### ISSUE THREAD

**Issue by bmerigan** [microsoft/DefinitelyTyped-tools#668]
Trying to access [https://typespublisher.blob.core.windows.net/typespublisher/index.html](https://typespublisher.blob.core.windows.net/typespublisher/index.html) no longer works.
In my case I'm seeing an error from a Node application: `getaddrinfo ENOTFOUND typespublisher.blob.core.windows.net`

Accessing via browser gets error `NS_ERROR_UNKNOWN_HOST`.
Was working ok a couple of days ago.

**Comment by andrewbranch** [comment]
This was never public API, and hasn’t been getting updated since 2020 anyway. (https://github.com/microsoft/DefinitelyTyped-tools/pull/51/files#diff-de7516b7f088e6c0b8ec69aee38be709e7d309719cb6f2c504280cd3c257c05dL21)

We finally deleted all the associated resources yesterday. But yeah, the data was 3 years stale.
